import SiteHeader from "@/components/layout/site-header"
import "./globals.css"

export const metadata = {
  title: "CRUD Med MongoDB & NextJS",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-dvh">
        <SiteHeader />
        <main className="px-[16rem] mt-6 h-full">
          {children}
        </main>
      </body>
    </html>
  )
}
